"""Install IDAMCP plugin into IDA's plugins directory.

Bundles the idamcp package and all dependencies directly into IDA's plugins
directory so that no sys.path manipulation or .venv is needed at runtime.

Usage:
    python install.py [--ida-dir "C:\\Program Files\\IDA Professional 9.0"]
    python install.py --python "C:\\...\\Python312\\python.exe"
    python install.py --uninstall [--ida-dir ...]
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import textwrap

DEFAULT_IDA_DIR = r"C:\Program Files\IDA Professional 9.0"
PLUGIN_FILENAME = "idamcp_plugin.py"
USER_PLUGINS_DIR = os.path.join(os.environ.get("APPDATA", os.path.expanduser("~")), "Hex-Rays", "IDA Pro", "plugins")
DEPS_DIRNAME = "idamcp_deps"


def _detect_ida_python(ida_dir: str) -> str | None:
    """Detect the Python executable that IDA is configured to use."""
    idapyswitch = os.path.join(ida_dir, "idapyswitch.exe")
    if not os.path.isfile(idapyswitch):
        return None

    try:
        result = subprocess.run(
            [idapyswitch],
            capture_output=True,
            text=True,
            input="\n",  # accept default
            timeout=10,
        )
        output = result.stdout + result.stderr
    except (subprocess.TimeoutExpired, OSError):
        return None

    # Look for "IDA previously used:" line — the currently configured Python
    match = re.search(r'IDA previously used:\s*"([^"]+)"', output)
    if match:
        dll_path = match.group(1)
        python_dir = os.path.dirname(dll_path)
        python_exe = os.path.join(python_dir, "python.exe")
        if os.path.isfile(python_exe):
            return python_exe

    # Fallback: first "Found:" entry
    for m in re.finditer(r'Found:\s*"([^"]+)"', output):
        found_dir = m.group(1).rstrip("\\")
        python_exe = os.path.join(found_dir, "python.exe")
        if os.path.isfile(python_exe):
            return python_exe

    return None


def _python_full_version(python_exe: str) -> str:
    """Return full version string for a Python executable."""
    return subprocess.run(
        [python_exe, "-c", "import sys; print(sys.version)"],
        capture_output=True,
        text=True,
    ).stdout.strip()


def _ensure_pip(python_exe: str) -> None:
    """Ensure pip is available for the given Python."""
    ret = subprocess.run(
        [python_exe, "-m", "pip", "--version"],
        capture_output=True,
    )
    if ret.returncode != 0:
        print("  pip not found, installing via ensurepip...")
        subprocess.run(
            [python_exe, "-m", "ensurepip", "--default-pip"],
            check=True,
        )


def _generate_loader(deps_dir: str) -> str:
    return textwrap.dedent(f"""\
        # Auto-generated by idamcp/install.py — do not edit manually.
        import sys

        _DEPS = r"{deps_dir}"
        if _DEPS not in sys.path:
            sys.path.insert(0, _DEPS)

        from idamcp.plugin import IdaMcpPlugin


        def PLUGIN_ENTRY():
            return IdaMcpPlugin()
    """)


def _install(ida_dir: str, python_override: str | None) -> None:
    project_dir = os.path.dirname(os.path.abspath(__file__))
    plugins_dir = USER_PLUGINS_DIR
    os.makedirs(plugins_dir, exist_ok=True)

    # 1. Find IDA's Python
    if python_override:
        python_exe = python_override
        if not os.path.isfile(python_exe):
            print(f"Error: Python not found at {python_exe}", file=sys.stderr)
            sys.exit(1)
    else:
        print("Detecting IDA's Python version...")
        python_exe = _detect_ida_python(ida_dir)
        if not python_exe:
            print(
                "Error: Could not detect IDA's Python.\n"
                "  Use --python to specify the path manually, e.g.:\n"
                '  python install.py --python "C:\\...\\Python312\\python.exe"',
                file=sys.stderr,
            )
            sys.exit(1)

    print(f"  IDA Python: {python_exe} ({_python_full_version(python_exe)})")

    # 2. Ensure pip is available
    _ensure_pip(python_exe)

    # 3. Clean previous install
    deps_dir = os.path.join(plugins_dir, DEPS_DIRNAME)
    if os.path.isdir(deps_dir):
        print("  Removing previous install...")
        try:
            shutil.rmtree(deps_dir)
        except PermissionError:
            # IDA may be locking .pyd/.dll files — rename aside for manual cleanup
            import glob, time
            # Try to clean up previous .old_* dirs
            for old in glob.glob(deps_dir + ".old_*"):
                shutil.rmtree(old, ignore_errors=True)
            old_dir = f"{deps_dir}.old_{int(time.time())}"
            os.rename(deps_dir, old_dir)
            print(f"  Warning: Could not remove (files locked by IDA?).")
            print(f"  Renamed to {old_dir} — delete it after closing IDA.")

    # 4. Install project + all dependencies into deps_dir
    #    --ignore-requires-python: IDA's Python version may be older than
    #    what pyproject.toml declares; the code is compatible regardless.
    print(f"  Installing idamcp and dependencies to {deps_dir} ...")
    subprocess.run(
        [
            python_exe, "-m", "pip", "install",
            "--target", deps_dir,
            "--ignore-requires-python",
            project_dir,
        ],
        check=True,
    )

    # 5. Generate loader script
    loader = _generate_loader(deps_dir)
    target = os.path.join(plugins_dir, PLUGIN_FILENAME)

    with open(target, "w", encoding="utf-8") as f:
        f.write(loader)

    print(f"\nInstalled successfully!")
    print(f"  Plugin: {target}")
    print(f"  Deps:   {deps_dir}")


def _uninstall(ida_dir: str) -> None:
    plugins_dir = USER_PLUGINS_DIR
    target = os.path.join(plugins_dir, PLUGIN_FILENAME)
    deps_dir = os.path.join(plugins_dir, DEPS_DIRNAME)

    removed = False
    if os.path.exists(target):
        os.remove(target)
        print(f"Removed: {target}")
        removed = True
    if os.path.isdir(deps_dir):
        shutil.rmtree(deps_dir)
        print(f"Removed: {deps_dir}")
        removed = True

    if not removed:
        print("Not installed.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Install IDAMCP plugin into IDA")
    parser.add_argument("--ida-dir", default=DEFAULT_IDA_DIR, help="IDA installation directory")
    parser.add_argument("--python", default=None, help="Path to Python executable matching IDA's version")
    parser.add_argument("--uninstall", action="store_true", help="Remove the plugin")
    args = parser.parse_args()

    if args.uninstall:
        _uninstall(args.ida_dir)
    else:
        _install(args.ida_dir, args.python)


if __name__ == "__main__":
    main()
