"""Install IDAMCP plugin into IDA's plugins directory for development.

Generates a loader script in IDA's plugins dir that adds the project's
source and .venv site-packages to sys.path, so code changes are reflected
immediately without reinstalling.

Usage:
    python install.py [--ida-dir "C:\\Program Files\\IDA Professional 9.0"]
    python install.py --uninstall [--ida-dir ...]
"""

from __future__ import annotations

import argparse
import os
import sys
import textwrap

DEFAULT_IDA_DIR = r"C:\Program Files\IDA Professional 9.0"
PLUGIN_FILENAME = "idamcp_plugin.py"


def _resolve_paths() -> tuple[str, str]:
    project_dir = os.path.dirname(os.path.abspath(__file__))
    venv_site_packages = os.path.join(project_dir, ".venv", "Lib", "site-packages")
    return project_dir, venv_site_packages


def _generate_loader(project_dir: str, venv_site_packages: str) -> str:
    return textwrap.dedent(f"""\
        # Auto-generated by idamcp/install.py — do not edit manually.
        import sys

        _PATHS = [
            r"{project_dir}",
            r"{venv_site_packages}",
        ]
        for _p in _PATHS:
            if _p not in sys.path:
                sys.path.insert(0, _p)

        from idamcp.plugin import PLUGIN_ENTRY  # noqa: F401, E402
    """)


def _install(ida_dir: str) -> None:
    plugins_dir = os.path.join(ida_dir, "plugins")
    if not os.path.isdir(plugins_dir):
        print(f"Error: plugins directory not found: {plugins_dir}", file=sys.stderr)
        sys.exit(1)

    project_dir, venv_site_packages = _resolve_paths()

    if not os.path.isdir(venv_site_packages):
        print(f"Warning: .venv not found at {venv_site_packages}", file=sys.stderr)
        print("Run 'uv sync --all-extras' first.", file=sys.stderr)
        sys.exit(1)

    loader = _generate_loader(project_dir, venv_site_packages)
    target = os.path.join(plugins_dir, PLUGIN_FILENAME)

    with open(target, "w", encoding="utf-8") as f:
        f.write(loader)

    print(f"Installed: {target}")
    print(f"  Project: {project_dir}")
    print(f"  Venv:    {venv_site_packages}")


def _uninstall(ida_dir: str) -> None:
    target = os.path.join(ida_dir, "plugins", PLUGIN_FILENAME)
    if os.path.exists(target):
        os.remove(target)
        print(f"Removed: {target}")
    else:
        print(f"Not installed: {target}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Install IDAMCP plugin into IDA")
    parser.add_argument("--ida-dir", default=DEFAULT_IDA_DIR, help="IDA installation directory")
    parser.add_argument("--uninstall", action="store_true", help="Remove the plugin")
    args = parser.parse_args()

    if args.uninstall:
        _uninstall(args.ida_dir)
    else:
        _install(args.ida_dir)


if __name__ == "__main__":
    main()
