"""Install IDAMCP plugin into IDA's plugins directory.

Bundles the idamcp package and all dependencies directly into IDA's plugins
directory so that no sys.path manipulation or .venv is needed at runtime.

Usage:
    python install.py [--ida-dir "C:\\Program Files\\IDA Professional 9.0"]
    python install.py --python "C:\\...\\Python312\\python.exe"
    python install.py --uninstall [--ida-dir ...]
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import textwrap

DEFAULT_IDA_DIR = r"C:\Program Files\IDA Professional 9.0"
PLUGIN_FILENAME = "idamcp_plugin.py"
DEPS_DIRNAME = "idamcp_deps"


def _detect_ida_python(ida_dir: str) -> str | None:
    """Detect the Python executable that IDA is configured to use."""
    idapyswitch = os.path.join(ida_dir, "idapyswitch.exe")
    if not os.path.isfile(idapyswitch):
        return None

    try:
        result = subprocess.run(
            [idapyswitch],
            capture_output=True,
            text=True,
            input="\n",  # accept default
            timeout=10,
        )
        output = result.stdout + result.stderr
    except (subprocess.TimeoutExpired, OSError):
        return None

    # Look for "IDA previously used:" line — the currently configured Python
    match = re.search(r'IDA previously used:\s*"([^"]+)"', output)
    if match:
        dll_path = match.group(1)
        python_dir = os.path.dirname(dll_path)
        python_exe = os.path.join(python_dir, "python.exe")
        if os.path.isfile(python_exe):
            return python_exe

    # Fallback: first "Found:" entry
    for m in re.finditer(r'Found:\s*"([^"]+)"', output):
        found_dir = m.group(1).rstrip("\\")
        python_exe = os.path.join(found_dir, "python.exe")
        if os.path.isfile(python_exe):
            return python_exe

    return None


def _python_full_version(python_exe: str) -> str:
    """Return full version string for a Python executable."""
    return subprocess.run(
        [python_exe, "-c", "import sys; print(sys.version)"],
        capture_output=True,
        text=True,
    ).stdout.strip()


def _ensure_pip(python_exe: str) -> None:
    """Ensure pip is available for the given Python."""
    ret = subprocess.run(
        [python_exe, "-m", "pip", "--version"],
        capture_output=True,
    )
    if ret.returncode != 0:
        print("  pip not found, installing via ensurepip...")
        subprocess.run(
            [python_exe, "-m", "ensurepip", "--default-pip"],
            check=True,
        )


def _generate_loader(deps_dir: str) -> str:
    return textwrap.dedent(f"""\
        # Auto-generated by idamcp/install.py — do not edit manually.
        import sys

        _DEPS = r"{deps_dir}"
        if _DEPS not in sys.path:
            sys.path.insert(0, _DEPS)

        import ida_idaapi
        import ida_kernwin


        class IdaMcpPlugin(ida_idaapi.plugin_t):
            flags = ida_idaapi.PLUGIN_KEEP
            comment = "MCP Server for IDA Python"
            help = "Exposes IDA Python execution via MCP over SSE"
            wanted_name = "IDAMCP"
            wanted_hotkey = "Ctrl-Shift-M"

            def init(self):
                try:
                    from idamcp.server import DEFAULT_HOST, DEFAULT_PORT, McpServerRunner
                except Exception as e:
                    ida_kernwin.msg(f"[IDAMCP] Failed to load: {{e}}\\n")
                    return ida_idaapi.PLUGIN_SKIP
                self._host = DEFAULT_HOST
                self._port = DEFAULT_PORT
                self._server = McpServerRunner(self._host, self._port)
                self._server.start()
                ida_kernwin.msg(f"[IDAMCP] Server started at http://{{self._host}}:{{self._port}}/sse\\n")
                return ida_idaapi.PLUGIN_KEEP

            def run(self, arg):
                if self._server.is_running:
                    self._server.stop()
                    ida_kernwin.msg("[IDAMCP] Server stopped\\n")
                else:
                    self._server.start()
                    ida_kernwin.msg(
                        f"[IDAMCP] Server started at http://{{self._host}}:{{self._port}}/sse\\n"
                    )
                return True

            def term(self):
                if self._server and self._server.is_running:
                    self._server.stop()
                    ida_kernwin.msg("[IDAMCP] Server stopped\\n")


        def PLUGIN_ENTRY():
            return IdaMcpPlugin()
    """)


def _install(ida_dir: str, python_override: str | None) -> None:
    project_dir = os.path.dirname(os.path.abspath(__file__))
    plugins_dir = os.path.join(ida_dir, "plugins")

    if not os.path.isdir(plugins_dir):
        print(f"Error: plugins directory not found: {plugins_dir}", file=sys.stderr)
        sys.exit(1)

    # 1. Find IDA's Python
    if python_override:
        python_exe = python_override
        if not os.path.isfile(python_exe):
            print(f"Error: Python not found at {python_exe}", file=sys.stderr)
            sys.exit(1)
    else:
        print("Detecting IDA's Python version...")
        python_exe = _detect_ida_python(ida_dir)
        if not python_exe:
            print(
                "Error: Could not detect IDA's Python.\n"
                "  Use --python to specify the path manually, e.g.:\n"
                '  python install.py --python "C:\\...\\Python312\\python.exe"',
                file=sys.stderr,
            )
            sys.exit(1)

    print(f"  IDA Python: {python_exe} ({_python_full_version(python_exe)})")

    # 2. Ensure pip is available
    _ensure_pip(python_exe)

    # 3. Clean previous install
    deps_dir = os.path.join(plugins_dir, DEPS_DIRNAME)
    if os.path.isdir(deps_dir):
        print("  Removing previous install...")
        shutil.rmtree(deps_dir)

    # 4. Install project + all dependencies into deps_dir
    print("  Installing idamcp and dependencies...")
    subprocess.run(
        [
            python_exe, "-m", "pip", "install",
            "--target", deps_dir,
            project_dir,
        ],
        check=True,
    )

    # 5. Generate loader script
    loader = _generate_loader(deps_dir)
    target = os.path.join(plugins_dir, PLUGIN_FILENAME)

    with open(target, "w", encoding="utf-8") as f:
        f.write(loader)

    print(f"\nInstalled successfully!")
    print(f"  Plugin: {target}")
    print(f"  Deps:   {deps_dir}")


def _uninstall(ida_dir: str) -> None:
    plugins_dir = os.path.join(ida_dir, "plugins")
    target = os.path.join(plugins_dir, PLUGIN_FILENAME)
    deps_dir = os.path.join(plugins_dir, DEPS_DIRNAME)

    removed = False
    if os.path.exists(target):
        os.remove(target)
        print(f"Removed: {target}")
        removed = True
    if os.path.isdir(deps_dir):
        shutil.rmtree(deps_dir)
        print(f"Removed: {deps_dir}")
        removed = True

    if not removed:
        print("Not installed.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Install IDAMCP plugin into IDA")
    parser.add_argument("--ida-dir", default=DEFAULT_IDA_DIR, help="IDA installation directory")
    parser.add_argument("--python", default=None, help="Path to Python executable matching IDA's version")
    parser.add_argument("--uninstall", action="store_true", help="Remove the plugin")
    args = parser.parse_args()

    if args.uninstall:
        _uninstall(args.ida_dir)
    else:
        _install(args.ida_dir, args.python)


if __name__ == "__main__":
    main()
